create table toa(

tecnico varchar(250),
id_recurso varchar(250),
numero_ot varchar(250),
subtipo_de_actividad varchar(250),
numero_de_peticion varchar(250),
fecha_de_cita varchar(250),
time_slot varchar(250),
sla_inicio varchar(250),
sla_fin varchar(250),
localidad varchar(250),
direccion varchar(250),
direccion_polar_x varchar(250),
direccion_polar_y varchar(250),
clave_zona_de_trabajo varchar(250),
zona_de_trabajo varchar(250),
nombre_cliente varchar(250),
tiempo_de_viaje varchar(250),
duracion_de_la_actividad varchar(250),
habilidad_del_trabajo varchar(250),
estado_actividad varchar(250),
pendiente_instancia_externa varchar(250),
categoria_de_capacidad varchar(250),
tecnologia_voz varchar(250),
validacion_tecnica varchar(250),
zona_rural varchar(250),
indicador_de_zona_peligrosa varchar(250),
enrutado_automatico_a_fecha varchar(250),
enrutado_automatico_a_recurso_nombre varchar(250),
enrutado_automatico_a_recurso varchar(250),
secuencia_en_ruta varchar(250),
primera_operacion_manual varchar(250), 
interfaz_de_primera_operacion_manual varchar(250),
primera_operacion_manual_realizada_por_usuario varchar(250),
primera_operacion_manual_realizada_por_usuario_conexion varchar(250),
primera_operacion_manual_realizada_por_usuario_nombre varchar(250),
hora_de_asignacion_de_actividad varchar(250),
alertas_de_cumplimiento varchar(250),
tipo_de_requerimiento varchar(250),
fecha_de_registro_legados varchar(250),
motivo_de_requerimiento varchar(250),
motivo_de_suspension varchar(250),
tipo_de_devolucion_instalaciones varchar(250),
motivo_no_realizado_instalacion varchar(250),
usuario varchar(250),
tipo_de_cita varchar(250),
estado_de_la_validacion_de_las_coordenadas varchar(250),
fecha_de_creacion_toa varchar(250),
observaciones_en_legados varchar(2000),
cuadrante varchar(250),
codigo_de_peticion varchar(250) 
)

--drop table toa
truncate table toa 
select count(1) from toa
select * from toa